# Generated by Django 5.1.3 on 2024-11-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingprofile',
            old_name='date_reported',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='missingprofile',
            name='profile_type',
            field=models.CharField(choices=[('person', 'Person'), ('animal', 'Animal')], default='person', max_length=10),
        ),
        migrations.AddField(
            model_name='missingprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
