# Generated by Django 5.1.3 on 2024-11-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missing_profiles', '0004_telegramuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
