# Generated by Django 5.1.3 on 2024-11-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missing_profiles', '0006_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
