# Generated by Django 5.1.3 on 2024-11-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_profiles', '0007_delete_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
