# Generated by Django 5.1.3 on 2024-11-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missing_profiles', '0008_telegramsubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramSubscriber',
        ),
    ]
