# Generated by Django 5.1.3 on 2024-11-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_profiles', '0009_delete_telegramsubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
