# Generated by Django 5.1.3 on 2024-11-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missing_profiles', '0010_telegramsubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramSubscriber',
        ),
    ]
