# Generated by Django 5.1.3 on 2024-11-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_profiles', '0011_delete_telegramsubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='missingprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='missingprofile',
            name='last_seen_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
