# Generated by Django 5.1.3 on 2024-11-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_profiles', '0012_missingprofile_latitude_missingprofile_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('relation_degree', models.CharField(max_length=255)),
                ('applicant_contact', models.CharField(max_length=20)),
                ('pet_type', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кот'), ('other', 'Другое')], max_length=20)),
                ('pet_gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('missing_region', models.CharField(max_length=255)),
                ('additional_regions', models.CharField(blank=True, max_length=255)),
                ('missing_area', models.CharField(max_length=255)),
                ('missing_date', models.DateField()),
                ('missing_time', models.TimeField()),
                ('search_area_type', models.CharField(choices=[('city', 'Город'), ('forest', 'Лес')], max_length=50)),
                ('disappearance_circumstances', models.TextField(blank=True)),
                ('distinctive_features', models.TextField(blank=True)),
                ('belongings', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('relation_degree', models.CharField(max_length=255)),
                ('applicant_contact', models.CharField(max_length=20)),
                ('missing_person_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другое')], max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('missing_region', models.CharField(max_length=255)),
                ('additional_regions', models.CharField(blank=True, max_length=255)),
                ('missing_person_contact', models.CharField(blank=True, max_length=20)),
                ('missing_area', models.CharField(max_length=255)),
                ('missing_date', models.DateField()),
                ('missing_time', models.TimeField()),
                ('police_report', models.BooleanField(default=False)),
                ('search_area_type', models.CharField(choices=[('city', 'Город'), ('forest', 'Лес')], max_length=50)),
                ('disappearance_circumstances', models.TextField(blank=True)),
                ('health_condition', models.TextField(blank=True)),
                ('clothing_description', models.TextField(blank=True)),
                ('distinctive_features', models.TextField(blank=True)),
                ('belongings', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MissingProfile',
        ),
    ]
